language: python

git:
  depth: false

matrix:
  include:
  - os: linux
    sudo: false
    python: '3.5'
    script: tox -e py35
  - os: linux
    sudo: false
    python: '3.6'
    script: tox -e py36
  - os: linux
    dist: xenial
    python: '3.7'
    sudo: true
    script: tox -e py37
  - os: osx
    language: objective-c
    script: tox -e py36

install:
  - pip install tox
  
before_script:
  # cc-test-reporter is the tool used to send test coverage information to CodeClimate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - pwd
  - ls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

branches:
  only:
  - "master"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
