env:
  global:
    - CC_TEST_REPORTER_ID=1efc0ae6a768b801598648d8e9842a781e3f08f6ee3557bbc5604a8d2dc1e6da

language: python

git:
  depth: false

matrix:
  include:
  - os: linux
    sudo: false
    python: '3.5'
    script: tox -e py35
  - os: linux
    sudo: false
    python: '3.6'
    script: tox -e py36
  - os: linux
    dist: xenial
    python: '3.7'
    sudo: true
    script: tox -e py37
  - os: osx
    language: objective-c
    script: tox -e py36

install:
  - pip install tox

branches:
  only:
  - "master"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
